name: instant-compiler
version: '1.0'
author: Mateusz Biegański

executables:
  insc_jvm:
    main:          insc_jvm.hs
    source-dirs:   src
  insc_llvm:
    main:          insc_llvm.hs
    source-dirs:   src

dependencies:
  - base >= 4.7 && < 5
  - text
  - array
  - containers
  - mtl
  - filepath
  - process
