name: instant-compiler
version: '1.0'
author: Mateusz Biegański

executables:
  app-exe:
    main:          insc_jvm.hs
    source-dirs:   src
#    dependencies:
#       - instant-compiler

dependencies:
  - base >= 4.7 && < 5
  - text
  - array
  - containers
  - mtl
