name: instant-compiler
version: '1.0'
author: Mateusz Biegański

executables:
  jvm:
    main:          insc_jvm.hs
    source-dirs:   src
  llvm:
    main:          insc_llvm.hs
    source-dirs:   src

dependencies:
  - base >= 4.7 && < 5
  - text
  - array
  - containers
  - mtl
